# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class V8MacroClaim(BaseModel):
    unit_id: typing.Optional[str] = None
    claim_id: typing.Optional[str] = None
    statement_type: typing.Optional[types.V8UserStatementType] = None
    coarse_type: typing.Optional[types.V8CoarseType] = None
    support_span_ids: typing.List[str]
    target_span_ids: typing.List[str]
    relation_span_ids: typing.List[str]
    subject_span_ids: typing.List[str]
    action_agent_span_ids: typing.List[str]
    action_recipient_span_ids: typing.List[str]
    experiencer_span_ids: typing.List[str]
    object_span_ids: typing.List[str]
    temporal_span_ids: typing.List[str]
    measurement_span_ids: typing.List[str]
    confidence: typing.Optional[float] = None

class V8MacroDiscourseAct(BaseModel):
    unit_id: typing.Optional[str] = None
    act_type: typing.Optional[types.V8DiscourseActType] = None
    evidence_span_ids: typing.List[str]
    confidence: typing.Optional[float] = None

class V8MacroSemanticOutput(BaseModel):
    schema_version: typing.Optional[typing_extensions.Literal['v8-macro-raw']] = None
    acts: typing.List["V8MacroDiscourseAct"]
    claims: typing.List["V8MacroClaim"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (3)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
V8MacroClaim.model_rebuild()
V8MacroDiscourseAct.model_rebuild()
V8MacroSemanticOutput.model_rebuild()
