# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class V8CoarseType(str, Enum):
    SYMPTOM = "SYMPTOM"
    STATE = "STATE"
    ACTION = "ACTION"
    EXPOSURE = "EXPOSURE"
    FOOD = "FOOD"
    MEDICATION = "MEDICATION"
    TIME = "TIME"
    MEASUREMENT = "MEASUREMENT"
    CONTEXT = "CONTEXT"

class V8DiscourseActType(str, Enum):
    ANSWER_NOW = "ANSWER_NOW"
    WANTS_TRIAGE = "WANTS_TRIAGE"
    CORRECTION = "CORRECTION"
    CLARIFICATION_REQUEST = "CLARIFICATION_REQUEST"
    FACT_STATEMENT = "FACT_STATEMENT"
    QUESTION = "QUESTION"
    REPORT_CONTEXT = "REPORT_CONTEXT"

class V8UserStatementType(str, Enum):
    REPORTS = "REPORTS"
    DENIES = "DENIES"
    REPORTS_NORMAL = "REPORTS_NORMAL"
    REPORTS_ABNORMAL = "REPORTS_ABNORMAL"
    UNCERTAIN = "UNCERTAIN"
    HISTORICAL = "HISTORICAL"
    HYPOTHETICAL = "HYPOTHETICAL"
    ASKS = "ASKS"
    CORRECTS = "CORRECTS"

# #########################################################################
# Generated classes (3)
# #########################################################################

class V8MacroClaim(BaseModel):
    unit_id: str
    claim_id: str
    statement_type: V8UserStatementType
    coarse_type: V8CoarseType
    support_span_ids: typing.List[str]
    target_span_ids: typing.List[str]
    relation_span_ids: typing.List[str]
    subject_span_ids: typing.List[str]
    action_agent_span_ids: typing.List[str]
    action_recipient_span_ids: typing.List[str]
    experiencer_span_ids: typing.List[str]
    object_span_ids: typing.List[str]
    temporal_span_ids: typing.List[str]
    measurement_span_ids: typing.List[str]
    confidence: float

class V8MacroDiscourseAct(BaseModel):
    unit_id: str
    act_type: V8DiscourseActType
    evidence_span_ids: typing.List[str]
    confidence: float

class V8MacroSemanticOutput(BaseModel):
    schema_version: typing_extensions.Literal['v8-macro-raw']
    acts: typing.List["V8MacroDiscourseAct"]
    claims: typing.List["V8MacroClaim"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (3)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
V8MacroClaim.model_rebuild()
V8MacroDiscourseAct.model_rebuild()
V8MacroSemanticOutput.model_rebuild()
