# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["V8MacroClaim","V8MacroDiscourseAct","V8MacroSemanticOutput",]
        ), enums=set(
          ["V8CoarseType","V8DiscourseActType","V8UserStatementType",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 3
    # #########################################################################

    @property
    def V8CoarseType(self) -> "V8CoarseTypeViewer":
        return V8CoarseTypeViewer(self)

    @property
    def V8DiscourseActType(self) -> "V8DiscourseActTypeViewer":
        return V8DiscourseActTypeViewer(self)

    @property
    def V8UserStatementType(self) -> "V8UserStatementTypeViewer":
        return V8UserStatementTypeViewer(self)


    # #########################################################################
    # Generated classes 3
    # #########################################################################

    @property
    def V8MacroClaim(self) -> "V8MacroClaimViewer":
        return V8MacroClaimViewer(self)

    @property
    def V8MacroDiscourseAct(self) -> "V8MacroDiscourseActViewer":
        return V8MacroDiscourseActViewer(self)

    @property
    def V8MacroSemanticOutput(self) -> "V8MacroSemanticOutputViewer":
        return V8MacroSemanticOutputViewer(self)



# #########################################################################
# Generated enums 3
# #########################################################################

class V8CoarseTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("V8CoarseType")
        self._values: typing.Set[str] = set([  "SYMPTOM",  "STATE",  "ACTION",  "EXPOSURE",  "FOOD",  "MEDICATION",  "TIME",  "MEASUREMENT",  "CONTEXT",  ])
        self._vals = V8CoarseTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "V8CoarseTypeValues":
        return self._vals


class V8CoarseTypeViewer(V8CoarseTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class V8CoarseTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def SYMPTOM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SYMPTOM"))
    
    @property
    def STATE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("STATE"))
    
    @property
    def ACTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ACTION"))
    
    @property
    def EXPOSURE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("EXPOSURE"))
    
    @property
    def FOOD(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FOOD"))
    
    @property
    def MEDICATION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MEDICATION"))
    
    @property
    def TIME(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("TIME"))
    
    @property
    def MEASUREMENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MEASUREMENT"))
    
    @property
    def CONTEXT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CONTEXT"))
    
    


class V8DiscourseActTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("V8DiscourseActType")
        self._values: typing.Set[str] = set([  "ANSWER_NOW",  "WANTS_TRIAGE",  "CORRECTION",  "CLARIFICATION_REQUEST",  "FACT_STATEMENT",  "QUESTION",  "REPORT_CONTEXT",  ])
        self._vals = V8DiscourseActTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "V8DiscourseActTypeValues":
        return self._vals


class V8DiscourseActTypeViewer(V8DiscourseActTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class V8DiscourseActTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def ANSWER_NOW(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ANSWER_NOW"))
    
    @property
    def WANTS_TRIAGE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("WANTS_TRIAGE"))
    
    @property
    def CORRECTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CORRECTION"))
    
    @property
    def CLARIFICATION_REQUEST(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CLARIFICATION_REQUEST"))
    
    @property
    def FACT_STATEMENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FACT_STATEMENT"))
    
    @property
    def QUESTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("QUESTION"))
    
    @property
    def REPORT_CONTEXT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REPORT_CONTEXT"))
    
    


class V8UserStatementTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("V8UserStatementType")
        self._values: typing.Set[str] = set([  "REPORTS",  "DENIES",  "REPORTS_NORMAL",  "REPORTS_ABNORMAL",  "UNCERTAIN",  "HISTORICAL",  "HYPOTHETICAL",  "ASKS",  "CORRECTS",  ])
        self._vals = V8UserStatementTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "V8UserStatementTypeValues":
        return self._vals


class V8UserStatementTypeViewer(V8UserStatementTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class V8UserStatementTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def REPORTS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REPORTS"))
    
    @property
    def DENIES(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("DENIES"))
    
    @property
    def REPORTS_NORMAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REPORTS_NORMAL"))
    
    @property
    def REPORTS_ABNORMAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REPORTS_ABNORMAL"))
    
    @property
    def UNCERTAIN(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("UNCERTAIN"))
    
    @property
    def HISTORICAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("HISTORICAL"))
    
    @property
    def HYPOTHETICAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("HYPOTHETICAL"))
    
    @property
    def ASKS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ASKS"))
    
    @property
    def CORRECTS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CORRECTS"))
    
    



# #########################################################################
# Generated classes 3
# #########################################################################

class V8MacroClaimAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("V8MacroClaim")
        self._properties: typing.Set[str] = set([  "unit_id",  "claim_id",  "statement_type",  "coarse_type",  "support_span_ids",  "target_span_ids",  "relation_span_ids",  "subject_span_ids",  "action_agent_span_ids",  "action_recipient_span_ids",  "experiencer_span_ids",  "object_span_ids",  "temporal_span_ids",  "measurement_span_ids",  "confidence",  ])
        self._props = V8MacroClaimProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "V8MacroClaimProperties":
        return self._props


class V8MacroClaimViewer(V8MacroClaimAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class V8MacroClaimProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def unit_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("unit_id"))
    
    @property
    def claim_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("claim_id"))
    
    @property
    def statement_type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("statement_type"))
    
    @property
    def coarse_type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("coarse_type"))
    
    @property
    def support_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("support_span_ids"))
    
    @property
    def target_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("target_span_ids"))
    
    @property
    def relation_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("relation_span_ids"))
    
    @property
    def subject_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("subject_span_ids"))
    
    @property
    def action_agent_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("action_agent_span_ids"))
    
    @property
    def action_recipient_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("action_recipient_span_ids"))
    
    @property
    def experiencer_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("experiencer_span_ids"))
    
    @property
    def object_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("object_span_ids"))
    
    @property
    def temporal_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("temporal_span_ids"))
    
    @property
    def measurement_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("measurement_span_ids"))
    
    @property
    def confidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("confidence"))
    
    


class V8MacroDiscourseActAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("V8MacroDiscourseAct")
        self._properties: typing.Set[str] = set([  "unit_id",  "act_type",  "evidence_span_ids",  "confidence",  ])
        self._props = V8MacroDiscourseActProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "V8MacroDiscourseActProperties":
        return self._props


class V8MacroDiscourseActViewer(V8MacroDiscourseActAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class V8MacroDiscourseActProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def unit_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("unit_id"))
    
    @property
    def act_type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("act_type"))
    
    @property
    def evidence_span_ids(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("evidence_span_ids"))
    
    @property
    def confidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("confidence"))
    
    


class V8MacroSemanticOutputAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("V8MacroSemanticOutput")
        self._properties: typing.Set[str] = set([  "schema_version",  "acts",  "claims",  ])
        self._props = V8MacroSemanticOutputProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "V8MacroSemanticOutputProperties":
        return self._props


class V8MacroSemanticOutputViewer(V8MacroSemanticOutputAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class V8MacroSemanticOutputProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def schema_version(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("schema_version"))
    
    @property
    def acts(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("acts"))
    
    @property
    def claims(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("claims"))
    
    

