# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.V8MacroClaim": types.V8MacroClaim,
    "stream_types.V8MacroClaim": stream_types.V8MacroClaim,

    "types.V8MacroDiscourseAct": types.V8MacroDiscourseAct,
    "stream_types.V8MacroDiscourseAct": stream_types.V8MacroDiscourseAct,

    "types.V8MacroSemanticOutput": types.V8MacroSemanticOutput,
    "stream_types.V8MacroSemanticOutput": stream_types.V8MacroSemanticOutput,


    "types.V8CoarseType": types.V8CoarseType,

    "types.V8DiscourseActType": types.V8DiscourseActType,

    "types.V8UserStatementType": types.V8UserStatementType,

}