##################################################################################################
# 文件: src/veterinary_agent/conversation_store/__init__.py
# 作用: 作为 ConversationStore 组件包的统一出口，集中暴露接口契约、DTO、枚举、领域错误和 SQLAlchemy 工厂。
# 边界: 外部包应从本文件导入 ConversationStore 公共契约，避免跨包直接引用内部实现模块。
##################################################################################################

from veterinary_agent.config import (
    ConversationStoreHistoryConfig,
    ConversationStoreMessageConfig,
    ConversationStoreSettings,
    load_conversation_store_settings,
)
from veterinary_agent.conversation_store.dto import (
    AppendAssistantSegmentCommandDto,
    AppendAssistantSegmentResultDto,
    AppendMessageCommandDto,
    AppendMessageResultDto,
    ArchiveSessionCommandDto,
    CloseSessionCommandDto,
    ConversationMessageDto,
    ConversationRequestContextDto,
    ConversationSessionDto,
    ConversationStoreDto,
    CreateAssistantMessageCommandDto,
    CreateAssistantMessageResultDto,
    EnsureSessionCommandDto,
    EnsureSessionResultDto,
    FinalizeAssistantMessageCommandDto,
    FinalizeAssistantMessageResultDto,
    GetRecentMessagesQueryDto,
    GetRecentMessagesResultDto,
    GetSessionQueryDto,
    JsonMap,
    ListMessagesBySessionQueryDto,
    ListMessagesBySessionResultDto,
    MessageAttachmentRefDto,
    MessageAttachmentRefInputDto,
    MessageSegmentDto,
    UpdateSessionStatusResultDto,
)
from veterinary_agent.conversation_store.enums import (
    ConversationErrorCode,
    ConversationMessageRole,
    ConversationMessageStatus,
    ConversationOperation,
    ConversationSessionStatus,
)
from veterinary_agent.conversation_store.errors import (
    ConversationStoreError,
    ConversationStoreErrorDto,
    build_conversation_store_error_dto,
    is_conversation_error_retryable_by_default,
)
from veterinary_agent.conversation_store.sqlalchemy_store import (
    CONVERSATION_ATTACHMENT_REF_TABLE,
    CONVERSATION_MESSAGE_SEGMENT_TABLE,
    CONVERSATION_MESSAGE_TABLE,
    CONVERSATION_SESSION_TABLE,
    CONVERSATION_STORE_METADATA,
    SqlAlchemyConversationMessageRepository,
    SqlAlchemyConversationReadRepository,
    SqlAlchemyConversationSessionRepository,
    SqlAlchemyConversationStore,
    create_sqlalchemy_conversation_store,
)
from veterinary_agent.conversation_store.store import (
    ConversationStore,
    TodoConversationStore,
)

__all__: tuple[str, ...] = (
    "AppendAssistantSegmentCommandDto",
    "AppendAssistantSegmentResultDto",
    "AppendMessageCommandDto",
    "AppendMessageResultDto",
    "ArchiveSessionCommandDto",
    "CONVERSATION_ATTACHMENT_REF_TABLE",
    "CONVERSATION_MESSAGE_SEGMENT_TABLE",
    "CONVERSATION_MESSAGE_TABLE",
    "CONVERSATION_SESSION_TABLE",
    "CONVERSATION_STORE_METADATA",
    "CloseSessionCommandDto",
    "ConversationErrorCode",
    "ConversationMessageDto",
    "ConversationMessageRole",
    "ConversationMessageStatus",
    "ConversationOperation",
    "ConversationRequestContextDto",
    "ConversationSessionDto",
    "ConversationSessionStatus",
    "ConversationStore",
    "ConversationStoreDto",
    "ConversationStoreError",
    "ConversationStoreErrorDto",
    "ConversationStoreHistoryConfig",
    "ConversationStoreMessageConfig",
    "ConversationStoreSettings",
    "CreateAssistantMessageCommandDto",
    "CreateAssistantMessageResultDto",
    "EnsureSessionCommandDto",
    "EnsureSessionResultDto",
    "FinalizeAssistantMessageCommandDto",
    "FinalizeAssistantMessageResultDto",
    "GetRecentMessagesQueryDto",
    "GetRecentMessagesResultDto",
    "GetSessionQueryDto",
    "JsonMap",
    "ListMessagesBySessionQueryDto",
    "ListMessagesBySessionResultDto",
    "MessageAttachmentRefDto",
    "MessageAttachmentRefInputDto",
    "MessageSegmentDto",
    "SqlAlchemyConversationMessageRepository",
    "SqlAlchemyConversationReadRepository",
    "SqlAlchemyConversationSessionRepository",
    "SqlAlchemyConversationStore",
    "TodoConversationStore",
    "UpdateSessionStatusResultDto",
    "build_conversation_store_error_dto",
    "create_sqlalchemy_conversation_store",
    "is_conversation_error_retryable_by_default",
    "load_conversation_store_settings",
)
