##################################################################################################
# 文件: src/veterinary_agent/agent_application_service/__init__.py
# 作用: 作为 AgentApplicationService 组件包统一出口，集中暴露应用契约、DTO、错误、端口、默认实现与 TODO 适配器。
# 边界: 外部包应从本文件导入应用服务能力，避免跨包直接引用内部实现模块。
##################################################################################################

from veterinary_agent.agent_application_service.dto import (
    AgentApplicationDto,
    AgentCancelTurnCommandDto,
    AgentCancelTurnResultDto,
    AgentGraphEventDto,
    AgentGraphTurnRequestDto,
    AgentGraphTurnResultDto,
    AgentReasoningDisplayDto,
    AgentReferenceDto,
    AgentResponseSegmentDto,
    AgentResumeTurnCommandDto,
    AgentTraceFinalizeCommandDto,
    AgentTraceStartCommandDto,
    AgentTraceWriteResultDto,
    AgentTurnAttachmentDto,
    AgentTurnDiagnosticsDto,
    AgentTurnEventDto,
    AgentTurnExecutionContextDto,
    AgentTurnExecutionOptionsDto,
    AgentTurnInputAttachmentDto,
    AgentTurnInputContentDto,
    AgentTurnInputItemDto,
    AgentTurnInputTextDto,
    AgentTurnOptionsDto,
    AgentTurnPublishCapabilitiesDto,
    AgentTurnRequestCommandDto,
    AgentTurnRequestContextDto,
    AgentTurnResultDto,
    AgentTurnTrustedIdentityDto,
    AgentVetResultDto,
    JsonMap,
)
from veterinary_agent.agent_application_service.enums import (
    AgentApplicationErrorCode,
    AgentApplicationOperation,
    AgentApplicationPhase,
    AgentTraceDeliveryStatus,
    AgentTraceFinalStatus,
    AgentTurnStatus,
)
from veterinary_agent.agent_application_service.errors import (
    AgentApplicationErrorDto,
    AgentApplicationServiceError,
    build_agent_application_error_dto,
    is_agent_application_error_retryable_by_default,
)
from veterinary_agent.agent_application_service.ports import (
    TODO_GRAPH_RUNTIME_ERROR_CODE,
    TODO_TRACE_STORE_ERROR_CODE,
    AgentGraphRuntime,
    AgentGraphRuntimeUnavailableError,
    AgentLogicTraceStore,
    TodoAgentGraphRuntime,
    TodoAgentLogicTraceStore,
)
from veterinary_agent.agent_application_service.service import (
    AgentApplicationService,
    DefaultAgentApplicationService,
)
from veterinary_agent.agent_application_service.trace import (
    LogicTraceAgentTraceStore,
)

__all__: tuple[str, ...] = (
    "TODO_GRAPH_RUNTIME_ERROR_CODE",
    "TODO_TRACE_STORE_ERROR_CODE",
    "AgentApplicationDto",
    "AgentApplicationErrorCode",
    "AgentApplicationErrorDto",
    "AgentApplicationOperation",
    "AgentApplicationPhase",
    "AgentApplicationService",
    "AgentApplicationServiceError",
    "AgentCancelTurnCommandDto",
    "AgentCancelTurnResultDto",
    "AgentGraphEventDto",
    "AgentGraphRuntime",
    "AgentGraphRuntimeUnavailableError",
    "AgentGraphTurnRequestDto",
    "AgentGraphTurnResultDto",
    "AgentLogicTraceStore",
    "AgentReasoningDisplayDto",
    "AgentReferenceDto",
    "AgentResponseSegmentDto",
    "AgentResumeTurnCommandDto",
    "AgentTraceDeliveryStatus",
    "AgentTraceFinalStatus",
    "AgentTraceFinalizeCommandDto",
    "AgentTraceStartCommandDto",
    "AgentTraceWriteResultDto",
    "AgentTurnAttachmentDto",
    "AgentTurnDiagnosticsDto",
    "AgentTurnEventDto",
    "AgentTurnExecutionContextDto",
    "AgentTurnExecutionOptionsDto",
    "AgentTurnInputAttachmentDto",
    "AgentTurnInputContentDto",
    "AgentTurnInputItemDto",
    "AgentTurnInputTextDto",
    "AgentTurnOptionsDto",
    "AgentTurnPublishCapabilitiesDto",
    "AgentTurnRequestCommandDto",
    "AgentTurnRequestContextDto",
    "AgentTurnResultDto",
    "AgentTurnStatus",
    "AgentTurnTrustedIdentityDto",
    "AgentVetResultDto",
    "DefaultAgentApplicationService",
    "JsonMap",
    "LogicTraceAgentTraceStore",
    "TodoAgentGraphRuntime",
    "TodoAgentLogicTraceStore",
    "build_agent_application_error_dto",
    "is_agent_application_error_retryable_by_default",
)
