##################################################################################################
# 文件: src/veterinary_agent/logic_trace_store/__init__.py
# 作用: 作为 LogicTraceStore 组件包统一出口，集中暴露 DTO、枚举、错误、端口、TODO 空壳和 SQLAlchemy 实现。
# 边界: 外部包应从本文件导入 LogicTraceStore 公共契约，避免跨包直接引用内部实现模块。
##################################################################################################

from veterinary_agent.logic_trace_store.dto import (
    AppendTraceEventCommandDto,
    BuildTraceProjectionCommandDto,
    FinalizeTraceCommandDto,
    GetTraceQueryDto,
    JsonMap,
    ListTracesQueryDto,
    LogicTraceQueryResultDto,
    LogicTraceSchemaValidationResultDto,
    LogicTraceStoreDto,
    LogicTraceStoreSettings,
    LogicTraceStreamEventDto,
    LogicTraceWriteResultDto,
    RecordCallSummaryCommandDto,
    RecordTraceArtifactCommandDto,
    StartTraceCommandDto,
    TraceArtifactDto,
    TraceCallSummaryDto,
    TraceDetailDto,
    TraceDto,
    TraceEventDto,
    TraceOutboxDto,
    TraceProjectionDto,
)
from veterinary_agent.logic_trace_store.enums import (
    LogicTraceErrorCode,
    LogicTraceFinalStatus,
    LogicTraceOperation,
    LogicTraceStatus,
    LogicTraceWriteStatus,
    TraceArtifactType,
    TraceCallStatus,
    TraceCallType,
    TraceOutboxStatus,
    TraceProjectionType,
)
from veterinary_agent.logic_trace_store.errors import (
    LogicTraceStoreError,
    LogicTraceStoreErrorDto,
    build_logic_trace_store_error_dto,
    is_logic_trace_error_retryable_by_default,
)
from veterinary_agent.logic_trace_store.schema import (
    LogicTraceSchemaValidator,
    TodoLogicTraceSchemaValidator,
)
from veterinary_agent.logic_trace_store.sqlalchemy_store import (
    LOGIC_TRACE_ARTIFACT_TABLE,
    LOGIC_TRACE_CALL_SUMMARY_TABLE,
    LOGIC_TRACE_EVENT_TABLE,
    LOGIC_TRACE_OUTBOX_TABLE,
    LOGIC_TRACE_PROJECTION_TABLE,
    LOGIC_TRACE_STORE_METADATA,
    LOGIC_TRACE_TABLE,
    SqlAlchemyLogicTraceStore,
    create_sqlalchemy_logic_trace_store,
)
from veterinary_agent.logic_trace_store.store import (
    TODO_TRACE_STORE_ERROR_CODE,
    LogicTraceStore,
    TodoLogicTraceStore,
)

__all__: tuple[str, ...] = (
    "AppendTraceEventCommandDto",
    "BuildTraceProjectionCommandDto",
    "FinalizeTraceCommandDto",
    "GetTraceQueryDto",
    "JsonMap",
    "LOGIC_TRACE_ARTIFACT_TABLE",
    "LOGIC_TRACE_CALL_SUMMARY_TABLE",
    "LOGIC_TRACE_EVENT_TABLE",
    "LOGIC_TRACE_OUTBOX_TABLE",
    "LOGIC_TRACE_PROJECTION_TABLE",
    "LOGIC_TRACE_STORE_METADATA",
    "LOGIC_TRACE_TABLE",
    "ListTracesQueryDto",
    "LogicTraceErrorCode",
    "LogicTraceFinalStatus",
    "LogicTraceOperation",
    "LogicTraceQueryResultDto",
    "LogicTraceSchemaValidationResultDto",
    "LogicTraceSchemaValidator",
    "LogicTraceStatus",
    "LogicTraceStore",
    "LogicTraceStoreDto",
    "LogicTraceStoreError",
    "LogicTraceStoreErrorDto",
    "LogicTraceStoreSettings",
    "LogicTraceStreamEventDto",
    "LogicTraceWriteResultDto",
    "LogicTraceWriteStatus",
    "RecordCallSummaryCommandDto",
    "RecordTraceArtifactCommandDto",
    "SqlAlchemyLogicTraceStore",
    "StartTraceCommandDto",
    "TODO_TRACE_STORE_ERROR_CODE",
    "TodoLogicTraceSchemaValidator",
    "TodoLogicTraceStore",
    "TraceArtifactDto",
    "TraceArtifactType",
    "TraceCallStatus",
    "TraceCallSummaryDto",
    "TraceCallType",
    "TraceDetailDto",
    "TraceDto",
    "TraceEventDto",
    "TraceOutboxDto",
    "TraceOutboxStatus",
    "TraceProjectionDto",
    "TraceProjectionType",
    "build_logic_trace_store_error_dto",
    "create_sqlalchemy_logic_trace_store",
    "is_logic_trace_error_retryable_by_default",
)
