##################################################################################################
# 文件: src/veterinary_agent/checkpoint_store/__init__.py
# 作用: 作为 CheckpointStore 组件包的统一出口，集中暴露接口契约、DTO、枚举和领域错误。
# 边界: 外部包应从本文件导入 CheckpointStore 公共契约，避免跨包直接引用内部实现模块。
##################################################################################################

from veterinary_agent.checkpoint_store.dto import (
    AcquireRunLockCommandDto,
    AcquireRunLockResultDto,
    CheckpointRequestContextDto,
    CheckpointSnapshotDto,
    CheckpointStoreDto,
    CheckpointSummaryDto,
    CheckpointThreadDto,
    EnsureThreadCommandDto,
    EnsureThreadResultDto,
    GetCheckpointQueryDto,
    GraphExecutionStateDto,
    JsonMap,
    ListCheckpointsQueryDto,
    ListCheckpointsResultDto,
    LoadLatestCheckpointQueryDto,
    LoadLatestCheckpointResultDto,
    LoadSessionStateQueryDto,
    LoadSessionStateResultDto,
    MarkSegmentPublishedCommandDto,
    MarkSegmentPublishedResultDto,
    ReleaseRunLockCommandDto,
    ReleaseRunLockResultDto,
    SaveCheckpointCommandDto,
    SaveCheckpointResultDto,
    SegmentPublishStateDto,
    SessionBusinessStateDto,
    TaskExecutionStateDto,
)
from veterinary_agent.checkpoint_store.enums import (
    CheckpointErrorCode,
    CheckpointOperation,
    CheckpointRecordStatus,
    CheckpointThreadStatus,
    SegmentPublishStatus,
)
from veterinary_agent.checkpoint_store.errors import (
    CheckpointStoreError,
    CheckpointStoreErrorDto,
    build_checkpoint_store_error_dto,
    is_checkpoint_error_retryable_by_default,
)
from veterinary_agent.checkpoint_store.checkpoint_mapper import (
    CHECKPOINT_BUSINESS_STATE_CHANNEL,
    CHECKPOINT_GRAPH_STATE_CHANNEL,
    CHECKPOINT_METADATA_ENVELOPE_KEY,
    CHECKPOINT_METADATA_MANAGED_FLAG,
    CheckpointTupleMapper,
)
from veterinary_agent.checkpoint_store.langgraph_reader import (
    LangGraphCheckpointReader,
    LangGraphCheckpointReaderBackend,
)
from veterinary_agent.checkpoint_store.langgraph_writer import (
    LangGraphCheckpointWriter,
    LangGraphCheckpointWriterBackend,
)
from veterinary_agent.checkpoint_store.langgraph_settings import (
    LANGGRAPH_POSTGRES_SETUP_ON_STARTUP_ENV_NAME,
    LANGGRAPH_STRICT_MSGPACK_ENV_NAME,
    LangGraphPostgresSaverSettings,
    load_langgraph_postgres_saver_settings,
)
from veterinary_agent.checkpoint_store.langgraph_provider import (
    LANGGRAPH_THREAD_ID_MAX_LENGTH,
    LangGraphCheckpointer,
    LangGraphPostgresSaverContextFactory,
    LangGraphPostgresSaverProvider,
    LangGraphRunnableConfig,
    build_langgraph_thread_config,
    create_async_postgres_saver_context,
)
from veterinary_agent.checkpoint_store.migrations import (
    DATABASE_URL_ENV_NAME,
    CheckpointStoreMigrationSettings,
    load_checkpoint_store_migration_settings,
)
from veterinary_agent.checkpoint_store.store import (
    CheckpointStore,
    TodoCheckpointStore,
)
from veterinary_agent.checkpoint_store.sqlalchemy_store import (
    CHECKPOINT_RUN_LOCK_TABLE,
    CHECKPOINT_SEGMENT_PUBLISH_TABLE,
    CHECKPOINT_STORE_METADATA,
    CHECKPOINT_THREAD_TABLE,
    SqlAlchemyCheckpointReadRepository,
    SqlAlchemyCheckpointRunLockRepository,
    SqlAlchemyCheckpointSegmentPublishRepository,
    SqlAlchemyCheckpointStore,
    SqlAlchemyCheckpointThreadRepository,
    create_sqlalchemy_checkpoint_store,
)
from veterinary_agent.checkpoint_store.sqlalchemy_version import (
    SqlAlchemyCheckpointVersionRepository,
)
from veterinary_agent.checkpoint_store.thread_ids import (
    CHECKPOINT_THREAD_ID_PREFIX,
    build_checkpoint_thread_id,
)
from veterinary_agent.config import (
    CheckpointStoreCheckpointConfig,
    CheckpointStoreHistoryConfig,
    CheckpointStoreRunLockConfig,
    CheckpointStoreSchemaConfig,
    CheckpointStoreSegmentPublishConfig,
    CheckpointStoreSettings,
    load_checkpoint_store_settings,
)

__all__: tuple[str, ...] = (
    "AcquireRunLockCommandDto",
    "AcquireRunLockResultDto",
    "CHECKPOINT_BUSINESS_STATE_CHANNEL",
    "CHECKPOINT_GRAPH_STATE_CHANNEL",
    "CHECKPOINT_METADATA_ENVELOPE_KEY",
    "CHECKPOINT_METADATA_MANAGED_FLAG",
    "CHECKPOINT_RUN_LOCK_TABLE",
    "CHECKPOINT_SEGMENT_PUBLISH_TABLE",
    "CHECKPOINT_STORE_METADATA",
    "CHECKPOINT_THREAD_ID_PREFIX",
    "CHECKPOINT_THREAD_TABLE",
    "CheckpointStoreMigrationSettings",
    "CheckpointErrorCode",
    "CheckpointOperation",
    "CheckpointRecordStatus",
    "CheckpointRequestContextDto",
    "CheckpointSnapshotDto",
    "CheckpointStore",
    "CheckpointStoreDto",
    "CheckpointStoreError",
    "CheckpointStoreErrorDto",
    "CheckpointStoreCheckpointConfig",
    "CheckpointStoreHistoryConfig",
    "CheckpointStoreRunLockConfig",
    "CheckpointStoreSchemaConfig",
    "CheckpointStoreSegmentPublishConfig",
    "CheckpointStoreSettings",
    "CheckpointSummaryDto",
    "CheckpointThreadDto",
    "CheckpointThreadStatus",
    "CheckpointTupleMapper",
    "DATABASE_URL_ENV_NAME",
    "EnsureThreadCommandDto",
    "EnsureThreadResultDto",
    "GetCheckpointQueryDto",
    "GraphExecutionStateDto",
    "JsonMap",
    "LANGGRAPH_POSTGRES_SETUP_ON_STARTUP_ENV_NAME",
    "LANGGRAPH_STRICT_MSGPACK_ENV_NAME",
    "LANGGRAPH_THREAD_ID_MAX_LENGTH",
    "LangGraphCheckpointReader",
    "LangGraphCheckpointReaderBackend",
    "LangGraphCheckpointWriter",
    "LangGraphCheckpointWriterBackend",
    "LangGraphCheckpointer",
    "LangGraphPostgresSaverContextFactory",
    "LangGraphPostgresSaverProvider",
    "LangGraphPostgresSaverSettings",
    "LangGraphRunnableConfig",
    "ListCheckpointsQueryDto",
    "ListCheckpointsResultDto",
    "LoadLatestCheckpointQueryDto",
    "LoadLatestCheckpointResultDto",
    "LoadSessionStateQueryDto",
    "LoadSessionStateResultDto",
    "MarkSegmentPublishedCommandDto",
    "MarkSegmentPublishedResultDto",
    "ReleaseRunLockCommandDto",
    "ReleaseRunLockResultDto",
    "SaveCheckpointCommandDto",
    "SaveCheckpointResultDto",
    "SegmentPublishStateDto",
    "SegmentPublishStatus",
    "SessionBusinessStateDto",
    "SqlAlchemyCheckpointReadRepository",
    "SqlAlchemyCheckpointRunLockRepository",
    "SqlAlchemyCheckpointSegmentPublishRepository",
    "SqlAlchemyCheckpointStore",
    "SqlAlchemyCheckpointThreadRepository",
    "SqlAlchemyCheckpointVersionRepository",
    "TaskExecutionStateDto",
    "TodoCheckpointStore",
    "build_checkpoint_store_error_dto",
    "build_checkpoint_thread_id",
    "build_langgraph_thread_config",
    "create_async_postgres_saver_context",
    "create_sqlalchemy_checkpoint_store",
    "is_checkpoint_error_retryable_by_default",
    "load_langgraph_postgres_saver_settings",
    "load_checkpoint_store_migration_settings",
    "load_checkpoint_store_settings",
)
